### ISSUE TITLE
Love your script!

### ISSUE THREAD

**Issue by inglesuniversal** [nextapps-de/fat#5]
My favorite demo is the animated cube. How can I make it bounce on the window and change its size as it tweens from side to size of the screen?

**Comment by ts-thomas** [comment]
You can take this example as a start, copy and paste to the bottom of the existing demo:

```js
var direction = false;

function getNextCoords(direction){

	return (

		direction ?

			[	Math.random() > 0.5 ? 0 : window.innerWidth - 400,
				(Math.random() * (window.innerHeight - 400)) >> 0 ]
		:
			[  (Math.random() * (window.innerWidth - 400)) >> 0,
				Math.random() > 0.5 ? 0 : window.innerHeight - 400 ]
	)
}

function bounce(){

	var coords = getNextCoords(direction = !direction);

	scene.animate(query(".wrap"), {

		translateX: {
			to: coords[0],
			unit: "px"
		},
		translateY: {
			to: coords[1],
			unit: "px"
		}
	}, {
		duration: 2000,
		callback: bounce
	});
}

bounce();
```

The value `400` is the viewport size of the cube, it is required to keep 3d perspective.

**Comment by inglesuniversal** [comment]
Hello... I tried the code above and it worked immediately!!!

However, the bouncing takes place on the lower right side of the screen.

Could you kindly take a look at the following URL and share with me, how I can make it bounce inside the entire viewport. 

https://mycloudvip.net/gardner/demo.html

NOTE: I only made it a bit slower.
